# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.6.5
_src_path: https://github.com/jupyterlab/extension-template
advanced: false
author_email: info@lightconeresearch.org
author_name: Lightcone Research
create_claude_symlink: true
create_gemini_symlink: false
has_ai_rules: true
has_binder: false
has_settings: true
kind: frontend-and-server
labextension_name: 'jupyterlab-lightcone'
project_short_description: The open AI workbench for scientific research.
python_name: jupyterlab_lightcone
repository: https://github.com/LightconeResearch/jupyterlab-lightcone
test: true

